# Generated by Django 5.0.6 on 2024-06-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippingaddress_shipping_address2_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='enail',
            new_name='email',
        ),
    ]
