# Generated by Django 5.0.6 on 2024-06-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_orderitem_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
